# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  panda_joint1: 0.0
  panda_joint2: 0.0
  panda_joint3: 0.0
  panda_joint4: 0.0
  panda_joint5: 0.0
  panda_joint6: 1.571
  ee_connector_joint: 0
  slider_joint: 0.0
